"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


from pathlib import Path
from decouple import config  # type: ignore

import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# from decouple import config
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(",")], default=["localhost", "0.0.0.0", "127.0.0.1"])
#ALLOWED_HOSTS = [*ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    #🍑⬇️ Pure Apps 🟢⬇️
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    #🟢 additional Apps 🟢👇
    "accounts",
    "blog",
    "rest_framework",
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    #  To use the TokenAuthentication scheme you'll need to configure the
    #  authentication classes to include TokenAuthentication

    'drf_spectacular', # این خط رو نگه دار، فقط همین!
    # 'include_docs_urls',
    # 'rest_framework_spectacular', # این خط رو پاک کن!
    'django_filters',
    'mail_templated', #با django-templated-email متفاوت است این ماژول
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",   
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# user manager config 
AUTH_USER_MODEL = "accounts.User" 
# this is the custom User model that  we created in accounts app 

# restframework settings
REST_FRAMEWORK = {
       'DEFAULT_FILTER_BACKENDS': [
           'django_filters.rest_framework.DjangoFilterBackend',
       ],
       'DEFAULT_PERMISSION_CLASSES': [
           'rest_framework.permissions.IsAuthenticated',
       ],
       'DEFAULT_AUTHENTICATION_CLASSES': [
           'rest_framework.authentication.BasicAuthentication',
           'rest_framework.authentication.SessionAuthentication',
           'rest_framework.authentication.TokenAuthentication',
           'rest_framework_simplejwt.authentication.JWTAuthentication',

       ],
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
   }

    # 'DEFAULT_VERSIONING_CLASS': 'drf_spectacular.versioning.SpectacularVersioning',
    # اگر خواستید کلاس شمای دیگری را اضافه کنید، معمولا برای هر APIView به صورت جداگانه تعیین می‌شود
    # یا با تغییر AutoSchema سفارشی سازی می‌شود، نه اینکه لیست باشد.
    # به جای 'include_docs_urls.openapi.AutoSchema' احتمالاً منظورتان چیزی شبیه به این بوده:
    # 'DEFAULT_SCHEMA_CLASS': 'path.to.your.custom.AutoSchema'
    # اما به طور پیش‌فرض، drf-spectacular با AutoSchema خود به خوبی کار می‌کند.
# }

SPECTACULAR_SETTINGS = {
       'TITLE': 'Django Core API',
       'DESCRIPTION':  'accounts و blog اسناد خودکاره برای ',
       'VERSION': '3.0.0',
       'SERVE_INCLUDE_SCHEMA': False,
       'CREATED BY':'Saber Modirian',
         
    # 👇👇 جادوی اصلی اینجاست 👇👇
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "displayRequestDuration": True, # Request Duration برای نمایش SWAGGER_UI  در  این خط رو اضافه کن! ✅
    },
       
   }

# Email Configuration
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp4dev'
EMAIL_PORT = 25
EMAIL_HOST_USER =''      # Replace with your Gmail address
EMAIL_HOST_PASSWORD = '' # Use an App Password if 2FA is enabled